[package]
name = "giffibot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[dependencies]
bitschess = { git = "https://github.com/miklaskarjalainen/BitsChess.git", rev = "7c7b2fd" }
lazy_static = "1.4.0"
